name: I want to Spend More Money
description: Create some new infrastructure
title: "[tfvars]: "
labels: ["spending-your-money"]
body:
  - type: markdown
    attributes:
      value: |
        Lets create some new infrastructure.

  - type: dropdown
    id: requestor
    attributes:
      label: requestor
      description: Who are you?
      options:
        - Jess
        - Rob
    validations:
      required: true

  - type: input
    id: resource_group_name
    attributes:
      label: resource_group_name
      description: The name of the resource group to create.
      placeholder: 'dbatools-azure-lab'
      value: 'dbatools-azure-lab'
    validations:
      required: true

  - type: input
    id: sql_instance_name
    attributes:
      label: sql_instance_name
      description: The name of the SQL instance.
      placeholder: 'dsoslo-server'
      value: 'dsoslo-server'
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: location
      description: The location for the resources.
      placeholder: 'westeurope'
      value: 'westeurope'
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: tags
      description: The tags to apply to the resources.
      placeholder: '{"for" : "dsoslo2023"}'
      value: '{"for" : "dsoslo2023"}'
    validations:
      required: false

  - type: input
    id: administrator_login
    attributes:
      label: administrator_login
      description: The admin login for the SQL instance.
      placeholder: 'sqladmin'
      value: 'sqladmin'
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: environment
      description: Pick the environment
      options:
        - dev
        - test
        - prod
      default: 0
    validations:
      required: true

  - type: dropdown
    id: minimum_tls_version
    attributes:
      label: minimum_tls_version
      description: Enable or disable minimum_tls_version
      options:
        - Disabled
        - Enabled
      default: 0
    validations:
      required: true

  - type: dropdown
    id: public_network_access
    attributes:
      label: public_network_access
      description: Enable or disable public_network_access
      options:
        - Disabled
        - Enabled
      default: 0
    validations:
      required: true

  - type: input
    id: active_directory_admin_user
    attributes:
      label: active_directory_admin_user
      description: The AD admin user for the SQL instance.
      placeholder: 'jess@jpomfret7gmail.onmicrosoft.com'
      value: 'jess@jpomfret7gmail.onmicrosoft.com'
    validations:
      required: true

  - type: input
    id: active_directory_admin_sid
    attributes:
      label: active_directory_admin_sid
      description: The AD admin SID for the SQL instance.
      placeholder: '0c97d81f-a7c6-40d4-9077-ade0dfbfe968'
      value: '0c97d81f-a7c6-40d4-9077-ade0dfbfe968'
    validations:
      required: true

  - type: input
    id: tenantid
    attributes:
      label: tenantid
      description: The tenant ID for the SQL instance.
      placeholder: 'f98042ad-9bbc-499d-adb4-17193696b9a3'
      value: 'f98042ad-9bbc-499d-adb4-17193696b9a3'
    validations:
      required: true

  - type: input
    id: sql_database_names
    attributes:
      label: sql_database_names
      description: The SQL database names to create on the SQL instance.
      placeholder: '["dsoslo-db", "dsoslo-db-cdc"]'
      value: '["dsoslo-db", "dsoslo-db-cdc"]'
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: I know what I'm doing
      description: By submitting this form, you agree that you know what you're doing.
      options:
        - label: Trust me...
          required: true
