name: Enter Terraform Variables
description: Create some new infrastructure
title: "[tfvars]: "
labels: ["tfvars", "infra"]
body:
  - type: markdown
    attributes:
      value: |
        Lets create some new infrastructure.

  - type: input
    id: resource_group_name
    attributes:
      label: Resource Group Name
      description: The name of the resource group to create.
    validations:
      required: true

  - type: input
    id: sql_instance_name
    attributes:
      label: SQL Instance Name
      description: The name of the SQL instance.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: The location for the resources.
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: The tags to apply to the resources.
      placeholder: '{"for" : "dsoslo2023"}'
    validations:
      required: false

  - type: input
    id: administrator_login
    attributes:
      label: Admin Login
      description: The admin login for the SQL instance.
      placeholder: 'sqladmin'
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Pick the environment
      options:
        - dev
        - test
        - prod
      default: 0
    validations:
      required: true

  - type: dropdown
    id: minimum_tls_version
    attributes:
      label: Minimum TLS Version
      description: Enable or disable minimum_tls_version
      options:
        - Disabled
        - Enabled
      default: 0
    validations:
      required: true

  - type: dropdown
    id: public_network_access
    attributes:
      label: Public Network Access
      description: Enable or disable public_network_access
      options:
        - Disabled
        - Enabled
      default: 0
    validations:
      required: true

  - type: input
    id: active_directory_admin_user
    attributes:
      label: AD Admin User
      description: The AD admin user for the SQL instance.
    validations:
      required: true      

  - type: input
    id: active_directory_admin_sid
    attributes:
      label: AD Admin SID
      description: The AD admin SID for the SQL instance.
    validations:
      required: true      

  - type: input
    id: tenantid
    attributes:
      label: Tenant ID
      description: The tenant ID for the SQL instance.
    validations:
      required: true      

  - type: input
    id: sql_database_names
    attributes:
      label: SQL Database Names
      description: The SQL database names to create on the SQL instance.
      placeholder: '["db1", "db2"]'
    validations:
      required: true      

  - type: checkboxes
    id: terms
    attributes:
      label: I know what I'm doing
      description: By submitting this form, you agree that you know what you're doing.
      options:
        - label: Trust me...
          required: true
