# when an issue is opened add the title and link to sql database

on:
  issues:
    types: 
      - opened

# default to pwsh
defaults:
  run:
    shell: pwsh

jobs:
  insert:
  # only run if issue is created by jess
    if: github.actor == 'jpomfret'
    runs-on: ubuntu-latest

    steps:
    
    # call api to insert data
    - name: Insert Issue Data
      id: insert_issue_data
      run: |
        $body = @{
          IssueTitle = '${{ github.event.issue.title }}'
          IssueNumber = '${{ github.event.issue.number }}'
          IssueLink = '${{ github.event.issue.html_url }}'
        }
        $bodyJson = $body | ConvertTo-Json
        $response = Invoke-RestMethod -Uri 'https://dsoslo2023.azurewebsites.net/api/InsertSqlData' -Method Post -Body $bodyJson -ContentType 'application/json'
        echo $response
